"""Cambios en la tabla Plaza

Revision ID: 08c291294e3a
Revises: 
Create Date: 2023-05-24 17:21:55.102058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08c291294e3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaza', schema=None) as batch_op:
        batch_op.alter_column('num_concursos_contratacion',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('fecha_cese',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaza', schema=None) as batch_op:
        batch_op.alter_column('fecha_cese',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('num_concursos_contratacion',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
