"""Cambio en el nombre de campos para evitar problemas con palabras reservadas

Revision ID: 333a0e002d6c
Revises: 84794a0ff805
Create Date: 2023-06-06 19:01:50.938999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '333a0e002d6c'
down_revision = '84794a0ff805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_flag', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('modification_flag', sa.Boolean(), nullable=False))
        batch_op.drop_column('modification')
        batch_op.drop_column('read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('modification', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('modification_flag')
        batch_op.drop_column('read_flag')

    # ### end Alembic commands ###
