"""Cambios en la tabla Docente

Revision ID: d85940cdff82
Revises: 08c291294e3a
Create Date: 2023-06-05 23:37:57.866209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd85940cdff82'
down_revision = '08c291294e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('modification', sa.Boolean(), nullable=False))
        batch_op.drop_index('email_3')
        batch_op.drop_index('email_4')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docente', schema=None) as batch_op:
        batch_op.create_index('email_4', ['email'], unique=False)
        batch_op.create_index('email_3', ['email'], unique=False)
        batch_op.drop_column('modification')
        batch_op.drop_column('query')

    # ### end Alembic commands ###
